# 服务端口号
server:
  port: 9001

spring:
  application:
    name: microservice-order-consumer # 对外暴露的服务名称

eureka:
  client:
    register-with-eureka: false
    service-url:
#      defaultZone: http://192.168.43.3:10001/eureka/,http://192.168.43.3:10002/eureka/,http://192.168.43.3:10003/eureka/
      defaultZone: http://192.168.43.3:10001/eureka/
  instance:
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3


# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
MICROSERVICE-ORDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
# 开启熔断
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false