# 服务端口号
server:
  port: 8001

spring:
  application:
    name: microservice-order # 对外暴露的服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/test4?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 5209
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.springcloud.entity  # 注意：对应实体类的路径

# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.43.3:10001/eureka/,http://192.168.43.3:10002/eureka/,http://192.168.43.3:10003/eureka/
      defaultZone: http://192.168.43.3:10001/eureka/
  instance:
    instance-id: 订单服务:8001 #显现服务信息
    prefer-ip-address: true #访问时可显示ip地址
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3
    status-page-url: http://192.168.43.3:${server.port}/swagger-ui.html

# 用来展示项目的基本信息
info:
  author.name: test
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}
# 配置hystrix dashboard的url访问
# 开启指标流端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream