# 服务端口号
server:
  port: 10001

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka01
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://192.168.43.3:10001/eureka/,http://192.168.43.3:10002/eureka/,http://192.168.43.3:10003/eureka/
      defaultZone: http://192.168.43.3:10001/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000